name: CI

on:
  workflow_dispatch:
  pull_request:
    branches: [main, beta, alpha]
  schedule:
    - cron: '0 3 * * *'

permissions: read-all

jobs:
  test_unit:
    name: Run Test Units
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout code'
        uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b

      - name: Use Node.js current version
        uses: actions/setup-node@64ed1c7eab4cce3362f8c340dee64e5eaeef8f7c
        with:
          node-version: current

      - name: Install dependency
        run: npm ci

      - name: Build output
        run: npm run build

      - name: Run Test Units
        run: npm run test
