name: CI (Pull Requests)

on:
  pull_request:
    branches: [main, beta, alpha]

permissions: read-all

jobs:
  test_unit:
    name: Run Test Units
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout code'
        uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608

      - name: Use Node.js current version
        uses: actions/setup-node@64ed1c7eab4cce3362f8c340dee64e5eaeef8f7c
        with:
          node-version: current

      - name: Install dependency
        run: npm ci

      - name: Build output
        run: npm run build

      - name: Run Test Units
        run: npm run test

      - name: Browser version testing
        uses: cypress-io/github-action@d69252d52b9a31bad4f418f05ba2bc83687a02eb
        with:
          command-prefix: '--'
          install: false
          browser: chrome
          build: npm run setup:client
          start: npm run start:client
