name: Scorecards

on:
  push:
    branches: [main]

permissions: read-all

jobs:
  scorecards:
    name: Scorecards Analysis
    runs-on: ubuntu-latest
    permissions:
      # Needed to upload the results to code-scanning dashboard.
      security-events: write
      # Used to receive a badge. (Upcoming feature)
      id-token: write
      actions: read
      contents: read

    steps:
      - name: 'Checkout code'
        uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b
        with:
          persist-credentials: false

      - name: 'Run analysis'
        uses: ossf/scorecard-action@99c53751e09b9529366343771cc321ec74e9bd3d
        with:
          results_file: results.sarif
          results_format: sarif
          repo_token: ${{ secrets.SCORECARD_READ_TOKEN }}
          publish_results: true

      - name: 'Upload to code-scanning'
        uses: github/codeql-action/upload-sarif@678fc3afe258fb2e0cdc165ccf77b85719de7b3c
        with:
          sarif_file: results.sarif
